export const SET_SPINNER_VISIBLE = 'SET_SPINNER_VISIBLE'
export const SET_FOOTER_VISIBLE = 'SET_FOOTER_VISIBLE'
export const SET_ROUTE_PARAMS = 'SET_ROUTE_PARAMS'
export const SET_ROUTE_QUERY_PARAMS = 'SET_ROUTE_QUERY_PARAMS'
